"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.useCompute = exports.useSubscribe = exports.useServices = exports.useService = exports.useGetService = exports.Consumer = exports.Provider = exports.Context = exports.ServiceProvider = exports.Service = void 0;
var service_1 = require("./service");
Object.defineProperty(exports, "Service", { enumerable: true, get: function () { return __importDefault(service_1).default; } });
var provider_1 = require("./provider");
Object.defineProperty(exports, "ServiceProvider", { enumerable: true, get: function () { return __importDefault(provider_1).default; } });
var context_1 = require("./context");
Object.defineProperty(exports, "Context", { enumerable: true, get: function () { return context_1.Context; } });
Object.defineProperty(exports, "Provider", { enumerable: true, get: function () { return context_1.Provider; } });
Object.defineProperty(exports, "Consumer", { enumerable: true, get: function () { return context_1.Consumer; } });
var use_1 = require("./use");
Object.defineProperty(exports, "useGetService", { enumerable: true, get: function () { return use_1.useGetService; } });
Object.defineProperty(exports, "useService", { enumerable: true, get: function () { return use_1.useService; } });
Object.defineProperty(exports, "useServices", { enumerable: true, get: function () { return use_1.useServices; } });
Object.defineProperty(exports, "useSubscribe", { enumerable: true, get: function () { return use_1.useSubscribe; } });
Object.defineProperty(exports, "useCompute", { enumerable: true, get: function () { return use_1.useCompute; } });
